name: "CD: Container Kasm"

on:
  push:
    tags:
      - "docker-kasm-v*.*.*"

jobs:
  publish:
    uses: ./.github/workflows/docker-reusable-publish.yml
    with:
      image_name: cua-ubuntu
      context_dir: libs/kasm
      tag_prefix: docker-kasm-v
      docker_hub_org: trycua
    secrets:
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
