name: "CD: Container Lumier"

on:
  push:
    branches:
      - main
    tags:
      - "docker-lumier-v*.*.*"
    paths:
      - "libs/lumier/**"
      - ".github/workflows/cd-container-lumier.yml"
      - ".github/workflows/docker-reusable-publish.yml"

jobs:
  publish:
    uses: ./.github/workflows/docker-reusable-publish.yml
    with:
      image_name: lumier
      context_dir: libs/lumier
      dockerfile_path: Dockerfile
      tag_prefix: docker-lumier-v
      docker_hub_org: trycua
    secrets:
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
