name: "CI: Container QEMU Windows"

on:
  pull_request:
    paths:
      - "libs/qemu-docker/windows/**"
      - ".github/workflows/ci-container-qemu-windows.yml"
      - ".github/workflows/docker-reusable-build.yml"

jobs:
  build:
    uses: ./.github/workflows/docker-reusable-build.yml
    with:
      image_name: cua-qemu-windows
      context_dir: libs/qemu-docker/windows
      dockerfile_path: Dockerfile
