name: "CI: cua-core"

on:
  pull_request:
    paths:
      - "libs/python/core/**"
      - ".github/workflows/ci-py-core.yml"
      - ".github/workflows/py-reusable-build.yml"

jobs:
  build:
    uses: ./.github/workflows/py-reusable-build.yml
    with:
      package_name: "core"
      package_dir: "libs/python/core"
