name: "CI: cua-bench"

on:
  pull_request:
    paths:
      - "libs/python/bench-ui/**"
      - ".github/workflows/ci-py-bench.yml"
      - ".github/workflows/py-reusable-build.yml"
  push:
    branches:
      - main
    paths:
      - "libs/python/bench-ui/**"
      - ".github/workflows/ci-py-bench.yml"
      - ".github/workflows/py-reusable-build.yml"

jobs:
  build:
    uses: ./.github/workflows/py-reusable-build.yml
    with:
      package_name: "bench"
      package_dir: "libs/python/bench-ui"
