name: "CI: cua-computer"

on:
  pull_request:
    paths:
      - "libs/python/computer/**"
      - ".github/workflows/ci-py-computer.yml"
      - ".github/workflows/py-reusable-build.yml"
  push:
    branches:
      - main
    paths:
      - "libs/python/computer/**"
      - ".github/workflows/ci-py-computer.yml"
      - ".github/workflows/py-reusable-build.yml"

jobs:
  build:
    uses: ./.github/workflows/py-reusable-build.yml
    with:
      package_name: "computer"
      package_dir: "libs/python/computer"
