name: "CI: Lume"
on:
  pull_request:
    paths:
      - "libs/lume/**"
      - ".github/workflows/ci-swift-lume.yml"

concurrency:
  group: lume-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Runner images: https://github.com/actions/runner-images

jobs:
  test:
    name: Test
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - run: uname -a
      - run: sudo xcode-select -s /Applications/Xcode_16.2.app # Swift 6.2
      - run: swift test
        working-directory: ./libs/lume
  build:
    name: Release build
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - run: uname -a
      - run: sudo xcode-select -s /Applications/Xcode_16.2.app # Swift 6.2
      - run: swift build --configuration release
        working-directory: ./libs/lume
